name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    env:
        DEVELOPER_DIR: /Applications/Xcode_11.1.app/Contents/Developer
    steps:
    - uses: actions/checkout@v1
    - name: swift build
      run: |
        swift build
    - name: swift build ios
      run: |
        sdk=`xcrun -sdk iphonesimulator -show-sdk-path`
        sdkVersion=`echo $sdk | sed -E 's/.*iPhoneSimulator(.*)\.sdk/\1/'`
        swift build  -Xswiftc "-sdk" -Xswiftc "$sdk" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios$sdkVersion-simulator"

